import React, { createContext, useContext, useState, useEffect } from 'react';
import { useGlobalAuth } from './AuthContext';
import { useProfiles } from '../hooks/useDatabase';

// Dicționar simplificat pentru textele principale din aplicație
const translations = {
  ro: {
    login: {
      welcome: 'Bine ai venit!',
      welcomeTitle: 'Conectare Cuplu',
      howToCall: 'Cum vrei să îți spunem?',
      connectPartner: 'Conectează-te cu partenerul tău',
      placeholderName: 'Introdu numele tău...',
      girl: 'Fată 👩',
      boy: 'Băiat 👨',
      saving: 'Se salvează...',
      continueBtn: 'Continuă',
      yourKey: 'Cheia ta de conectare:',
      sendKey: 'Trimite această cheie partenerului, sau...',
      enterKey: 'Introdu tu cheia partenerului:',
      placeholderKey: 'ex: ABCDEF',
      youAreGirl: 'Ești Fată 👩',
      youAreBoy: 'Ești Băiat 👨',
      connecting: 'Se conectează...',
      connectBtn: 'Conectare',
      loginTab: 'Logare',
      registerTab: 'Cont Nou',
      emailLabel: 'Email',
      passLabel: 'Parola',
      passRules: 'Parola (min 6 caractere)',
      forgotPass: 'Ai uitat parola?',
      enterBtn: 'Intră',
      registerBtn: 'Creează Cont',
      forgotText: 'Îți vom trimite un link de resetare pe email.',
      resetBtn: 'Resetează Parola',
      backToLogin: 'Înapoi la Logare',
      logout: 'Deconectare',
      autoUpdate: 'Dacă partenerul tău introduce cheia ta, ecranul se va actualiza automat!',
      backConfirm: 'Vrei să te întorci și să schimbi numele sau genul? (Acest lucru va genera o altă cheie)',
      backBtn: 'Înapoi',
      footer: 'Făcut cu 💕 pentru voi',
      signIn: 'Intră în cont',
      createAcc: 'Creează cont',
      errorEmail: 'Introdu adresa de email',
      successReset: 'Link de resetare trimis pe email!',
      logoutConfirm: 'Vrei să te deconectezi?',
    },
    calendar: {
      months: ['Ianuarie', 'Februarie', 'Martie', 'Aprilie', 'Mai', 'Iunie', 'Iulie', 'August', 'Septembrie', 'Octombrie', 'Noiembrie', 'Decembrie'],
      days: ['Lu', 'Ma', 'Mi', 'Jo', 'Vi', 'Sâ', 'Du'],
      deleteConfirm: 'Sigur vrei să ștergi acest eveniment?',
      loading: 'Se încarcă Calendarul...',
      eventsOn: 'Evenimente pe',
      title: 'Calendar 📅',
      subtitle: 'Zilele noastre speciale',
      hint: '💡 Apasă pe orice zi pentru a adăuga un eveniment. Apasă pe un eveniment pentru a-l edita.',
      editTitle: 'Editează Eveniment ✏️',
      addTitle: 'Adaugă Eveniment ✨',
      defaultEventName: 'Eveniment',
      addAnother: '+ Adaugă alt eveniment în această zi',
      eventNameLabel: 'Nume Eveniment',
      dateLabel: 'Data',
      recurrenceLabel: 'Repetare',
      recNone: 'Doar o dată',
      recWeekly: 'La 7 zile',
      recMonthly: 'În fiecare lună',
      recYearly: 'În fiecare an',
      detailsLabel: 'Detalii (opțional)',
      detailsPlaceholder: 'Mai multe detalii despre eveniment...',
      importanceLabel: 'Importanță',
      high: 'Mare ❤️',
      medium: 'Medie 💛',
      low: 'Mică 💙',
      saveBtn: 'Salvează',
      deleteBtn: 'Șterge',
      cancelBtn: 'Anulează'
    },
    todo: {
      categories: {
        general: 'General',
        home: 'Casă 🏠',
        work: 'Muncă 💼',
        shopping: 'Cumpărături 🛒',
        health: 'Sănătate 💊',
        love: 'Iubire ❤️',
        other: 'Altele'
      },
      loading: 'Încărcare...',
      title: '📝 To-Do List',
      subtitle: 'Task-urile tale personale',
      tabActive: 'Active',
      tabCompleted: 'Istoric',
      sortImportance: '🔥 Sortare: Importanță',
      sortDeadline: '⏰ Sortare: Deadline',
      sortCategory: '📂 Sortare: Categorie',
      sortDateAdded: '📅 Sortare: Dată Adăugare',
      sortName: '🔤 Sortare: Nume',
      addBtn: '➕ Adaugă un task nou',
      emptyActive: 'Nu ai niciun task activ. Yay! 🎉',
      emptyCompleted: 'Nu ai niciun task finalizat încă.',
      expired: 'Expirat ⚠️',
      today: 'Azi 🚨',
      importance: 'Importanță:',
      impHigh: 'Mare',
      impMedium: 'Medie',
      impLow: 'Mică',
      impHighEmoji: '🔥 Mare',
      impMediumEmoji: '⭐ Medie',
      impLowEmoji: '🧊 Mică',
      editTask: 'Editează Task',
      newTask: 'Task Nou',
      titleLabel: 'Titlu *',
      titlePlaceholder: 'Ex: Cumpără flori',
      categoryLabel: 'Grupă / Categorie',
      otherCategory: 'Altă categorie...',
      newCategoryPlaceholder: 'Nume categorie nouă...',
      deadlineLabel: 'Termen limită (Deadline)',
      detailsLabel: 'Detalii (opțional)',
      detailsPlaceholder: 'Detalii adiționale...',
      importanceLabel: 'Importanță',
      imageLabel: 'Adaugă o imagine (opțional)',
      uploading: 'Se încarcă...',
      clickUpload: '📷 Apasă pentru a încărca o poză',
      deleteImage: 'Șterge imaginea',
      saveChanges: 'Salvează modificările',
      createTask: 'Creează task',
      errorImage: 'Eroare la încărcarea imaginii.'
    },
    memories: {
      openMap: '🗺️ Deschide în Google Maps',
      commentsReactions: 'Comentarii & Reacții 💕',
      addReactionPlaceholder: 'Adaugă o reacție...',
      send: 'Trimite',
      pleaseAddPhoto: 'Te rog adaugă o poză!',
      pleaseClickMap: 'Te rog dă click pe hartă pentru a alege locația!',
      errorImage: 'Eroare la procesarea imaginii',
      newPhoto: 'Poză nouă',
      editMemory: 'Editează Amintirea ✏️',
      addPhotoGallery: 'Adaugă Poză în Galerie 📸',
      addMemoryNew: 'Adaugă Amintire Nouă ✨',
      locSelected: '📍 Locație selectată pe hartă',
      locKept: '📍 Locație existentă păstrată',
      titlePlaceholder: 'Titlu (ex: Prima Vacanță)',
      descPlaceholder: 'Descriere...',
      emojiPlaceholder: 'Emoji (ex: 🏖️)',
      changeSelectedPhoto: 'Schimbă Poza selectată',
      replaceCurrentPhoto: 'Înlocuiește poza curentă (Opțional)',
      selectPhoto: 'Selectează o Poză (Obligatoriu la Galerie)',
      cancel: 'Anulează',
      saving: 'Se salvează...',
      save: 'Salvează',
      add: 'Adaugă',
      photoGallery: 'Galerie Foto 📸',
      addOnlyPhoto: '+ Adaugă doar o Poză',
      noPhotosYet: 'Nu aveți poze adăugate încă.',
      loadingMemories: 'Încărcare amintiri...',
      confirmDelete: 'Sigur vrei să ștergi această amintire/poză?',
      ourMemories: 'Amintirile Noastre 💕',
      specialPlaces: 'Locurile și momentele speciale',
      mapHint: '💡 Apasă oriunde pe hartă pentru a adăuga o amintire nouă!',
      savedLocations: 'Locații Salvate 📍',
      noMemoriesOnMap: 'Nu există amintiri pe hartă încă.'
    },
    messages: {
      loading: 'Încărcare mesaje...',
      seenAt: 'Văzut la ',
      seen: 'Văzut',
      back: 'Înapoi',
      typing: 'scrie...',
      writeMessagePlaceholder: 'Scrie un mesaj...',
      birthday: '🎂 Zi de naștere:',
      favColor: '🎨 Culoare preferată:',
      backToChat: 'Înapoi la chat'
    },
    games: {
      noOptions: 'Nicio opțiune',
      wheelAriaLabel: 'Roata norocului',
      spinning: '⏳ Se învârte...',
      spin: '🎲 Învârte!',
      finalDecision: 'Decizia finală:',
      tryAgain: '🔄 Încearcă din nou',
      addNewOption: 'Adaugă Opțiune Nouă',
      pizzaPlaceholder: 'Ex: Pizza',
      bgColor: 'Culoare fundal:',
      cancel: 'Anulează',
      add: 'Adaugă',
      todaysOptions: 'Opțiunile de azi:',
      addBtn: '+ Adaugă',
      noOptionsAddSome: 'Nicio opțiune. Adaugă câteva!',
      ideasFood: 'Idei & Mâncare 💡',
      letFateDecide: 'Lasă soarta să decidă pentru voi',
      foodTab: '🍔 Mâncare',
      datesTab: '🌹 Date-uri',
      loading: 'Încărcare...',
      loadDefaultsBtn: '🪄 Încarcă ideile predefinite',
      foodTitle: 'Ce mâncăm deseară? 🍽️',
      foodSubtitle: 'Apasă roata și lasă soarta să decidă!',
      dateTitle: 'Ce facem azi? 🌹',
      dateSubtitle: 'O idee perfectă de date!',
      defaults: {
        food: ['Pizza 🍕', 'Sushi 🍣', 'Burger 🍔', 'Paste 🍝', 'Chinezesc 🍜', 'Salată 🥗'],
        date: ['Film acasă 🎬', 'Plimbare 🚶', 'Gătim ceva 👨‍🍳', 'Jocuri video 🎮', 'Ieșim în oraș 🍷', 'Spa acasă 💆‍♀️']
      }
    },
    truthDare: {
      noOptions: 'Nicio opțiune',
      wheelAriaLabel: 'Roata norocului',
      spinning: '⏳ Se învârte...',
      spin: '🎲 Învârte!',
      yourChallengeIs: 'Provocarea ta este:',
      tryAgain: '🔄 Încearcă din nou',
      addQuestion: 'Adaugă o întrebare',
      bgColor: 'Culoare fundal:',
      cancel: 'Anulează',
      add: 'Adaugă',
      availableQuestions: 'Întrebările/Provocările disponibile:',
      addBtn: '+ Adaugă',
      noOptionsAddSome: 'Nicio opțiune. Adaugă câteva!',
      title: 'Truth or Dare 🎭',
      subtitle: 'Cine cutează... câștigă 😈',
      truthTab: '🤍 Adevăr',
      dareTab: '🔥 Provocare',
      loading: 'Încărcare...',
      truthTitle: 'Adevăr 🤍',
      truthSubtitle: 'Roata alege întrebarea. Nu poți minți!',
      dareTitle: 'Provocare 🔥',
      dareSubtitle: 'Roata alege provocarea. Curaj!',
      truthPlaceholder: 'Ex: Care e cel mai mare secret al tău?',
      darePlaceholder: 'Ex: Fă 10 genuflexiuni acum!',
      defaults: {
        truths: [
          'Care e cel mai mare secret al tău?',
          'Ce te sperie cel mai mult în viață?',
          'Care e momentul de care îți e cel mai rușine?',
          'Dacă ai putea schimba ceva la tine, ce ar fi?',
          'Care e cel mai mare vis al tău neîmplinit?',
          'Ce calitate apreciezi cel mai mult la mine?',
          'Care e amintirea ta preferată cu noi?',
          'Ce te-a atras prima dată la mine?',
          'Cel mai mare secret pe care nu l-ai spus nimănui?',
          'Cum îți imaginezi viața noastră peste 10 ani?'
        ],
        dares: [
          'Mimează personajul preferat din filme!',
          'Cântă 30s din melodia ta preferată!',
          'Fă 10 flotări acum!',
          'Spune 3 lucruri pe care le admiri la mine!',
          'Dansează 1 minut fără muzică!',
          'Vorbește cu accent 2 minute!',
          'Fă o poză haioasă și trimite-mi-o!',
          'Imită 3 emoji-uri diferite!',
          'Spune cât mai multe cuvinte în 30 secunde!',
          'Fă o glumă (bună sau proastă)!'
        ]
      }
    },
    movies: {
      recommendationsTitle: 'Recomandări',
      library: 'Librărie',
      coupleMatch: 'Couple Match',
      searchPlaceholder: 'Caută un film sau serial...',
      recommendedForYou: 'Recomandate pentru tine ✨',
      seeMore: 'Vezi mai multe ➔',
      likeSomeMovies: 'Apreciază (❤️) câteva filme sau seriale pentru a primi recomandări personalizate!',
      popularNow: 'Populare Acum 🔥',
      loading: 'Se încarcă...',
      exploreCatalog: 'Exploarează Catalogul ➔',
      moviesFound: 'Filme Găsite',
      tvFound: 'Seriale Găsite',
      noResults: 'Nu am găsit niciun rezultat.',
      noOverview: 'Nicio descriere disponibilă în limba română.',
      cast: 'Distribuție',
      noPicture: 'Fără Poză',
      watchTrailer: '▶️ Urmărește Trailer',
      notForMe: 'Nu e pentru mine',
      addToMyList: 'Adaugă în Lista Mea',
      saved: '✅ Salvat',
      add: '❤️ Adaugă',
      like: 'Îmi place',
      liked: '✅ Ai dat Like',
      likeBtn: '❤️ Îmi place',
      youLikeIt: 'Îți place',
      inYourList: 'În Lista Ta',
      emptyLibrary: 'Librăria e goală',
      emptyLibraryDesc: 'Filmele pe care le apreciezi (❤️) vor apărea aici pentru a le putea viziona mai târziu.',
      searchMovies: 'Caută Filme',
      loadingDetails: 'Se încarcă detaliile...',
      removeFromList: '❌ Elimină din Listă'
    },
    studyLobby: {
      todo: 'De făcut',
      inProgress: 'În lucru',
      done: 'Gata ✓',
      preparingRoom: 'Se pregătește sala de studiu...',
      studyRoom: '📚 Sala de Studiu',
      offline: 'offline',
      lobby: '🌳 Lobby',
      tasksTab: '📋 Task-uri',
      bonsaiInfoTitle: 'Cum crește Bonsaiul?',
      bonsaiInfo1: 'Copăcelul vostru (Bonsaiul) este o reflectare a timpului petrecut învățând sau lucrând.',
      bonsaiInfo2a: 'pentru fiecare ',
      bonsaiInfo2b: '1 minut',
      bonsaiInfo2c: ' de focus completat de oricare din voi.',
      bonsaiInfo3a: 'Dacă învățați amândoi ',
      bonsaiInfo3b: 'în același timp',
      bonsaiInfo3c: ', primiți un bonus de ',
      bonsaiInfo3d: '+50% XP',
      bonsaiInfo3e: '!',
      bonsaiInfo4: 'Punctele se adună la un fond comun (XP Total). Bonsaiul are mai multe etape, care se deblochează pe măsură ce creșteți XP-ul.',
      stageSeed: 'Sămânță',
      stageSprout: 'Răsad',
      stageSapling: 'Puiet',
      stageYoungTree: 'Copac Tânăr',
      stageMature: 'Bonsai Matur',
      stageAncient: 'Bonsai Străvechi',
      stageLegendary: 'Arborele Iubirii',
      stageBush: 'Arbust',
      stageTree: 'Copac',
      stageBlossom: 'Bonsai Înflorit',
      bonsaiInfo5: 'Rămâneți concentrați și lăsați copăcelul să crească alături de voi! 🌱',
      sessionsCompletedText: 'sesiuni completate',
      bonusCoStudy: '+50% XP bonus co-study!',
      sessionSettings: 'Setări Sesiune',
      workMin: 'Muncă (min)',
      breakMin: 'Pauză (min)',
      cycles: 'Cicluri',
      hurray: '🎉 Huraa!',
      finishedAllCycles1: 'Ai terminat toate cele ',
      finishedAllCycles2: ' cicluri de studiu!',
      startNewSession: 'Începe o nouă sesiune',
      focusTime: '💻 Focus Time',
      breakTime: '☕ Pauză',
      cycle: 'Ciclul',
      of: 'din',
      minFocus: 'min focus',
      minBreak: 'min pauză',
      start: '▶ Start',
      pause: '⏸ Pauză',
      reset: '↻ Reset',
      skipToBreak: '⏭ Sari la Pauză',
      skipToWork: '⏭ Sari la Muncă',
      music: '🎵 Muzică',
      on: '🔊 On',
      off: '🔇 Off',
      change: 'Schimbă ▾',
      radioLoop: 'Radio / Audio Loop',
      audioNotSupported: 'Browserul nu suportă elementul audio.',
      searchYoutube: '▶️ Caută pe YouTube',
      myTasks: 'Task-urile mele',
      whatToDo: 'Ce ai de făcut?',
      subjectOptional: 'Materie / Subiect (opțional)',
      addBtn: 'Adaugă',
      noTasksYet: 'Niciun task încă. Adaugă unul! 📝',
      deleteTaskPrompt: 'Ștergi acest task?',
      partnerNoTasks: 'nu are task-uri încă.'
    },
    homePlanner: {
      kitchen: 'Bucătărie',
      living: 'Living',
      bedroom: 'Dormitor',
      bathroom: 'Baie',
      hallway: 'Hol',
      balcony: 'Balcon',
      attic: 'Pod',
      office: 'Birou',
      freeSearches: 'Căutări Libere',
      superMatchTitlePush: 'Super Match la Design! 🌟',
      superMatchBodyPush: 'S-a creat un match nou: ',
      superMatchTitleInApp: 'Super Match! 🌟',
      superMatchBodyInApp: 'Amândoi ați apreciat: ',
      loadingProject: 'Se încarcă proiectul...',
      saved: 'salvate',
      all: 'Toate',
      addedItems: 'Elemente Adăugate 🛒',
      openLink: '🔗 Deschide Link',
      noPicture: '🔗 Fără Poză',
      viewLink: '🔗 Vezi Link',
      swipeIdeas: 'Idei din Swipe 💡',
      link: '🔗 Link',
      emptyRoom: 'Nu ai salvat încă nimic aici. Folosește butonul + sau Swipe.',
      ourProject: 'Proiectul Nostru 🏠',
      totalIdeasSaved: 'Total idei salvate: ',
      ideasAddedByYou: 'Idei/Link-uri adăugate de voi: ',
      superMatches: 'Super Matches: ',
      estimatedCost: '💰 Cost estimativ cumulat: ~',
      searchSavedIdeas: 'Caută în ideile salvate (după titlu, tag sau link)...',
      rooms: 'Camere',
      item: 'element',
      items: 'elemente',
      currency: 'RON',
      searchResults: 'Rezultate Căutare',
      noIdeasFor: 'Nu am găsit nicio idee pentru ',
      searchLabel: 'Căutare: ',
      searchPlaceholderSwipe: 'Caută în engleză pt rezultate optime (ex: black sofa)...',
      orChooseRoom: 'Sau alege o cameră:',
      backBtn: '← Înapoi',
      searchingPremiumIdeas: 'Se caută idei premium... ⏳',
      planBWarning: '⚠️ Folosim Pinterest-ul local (Plan B)',
      seenItAll: 'Ai văzut tot!',
      searchMore: 'Mai caută',
      noMatchesYet: 'Încă nu aveți potriviri aprobate amândoi.',
      approvedDecisions: 'Decizii Aprobate (Match-uri) 🌟',
      homePlannerTitle: 'Home Planner 🏡',
      homePlannerSubtitle: 'Proiectul pentru cuibușorul nostru',
      projectTab: 'Proiect',
      inspirationTab: 'Inspirație',
      matchesTab: 'Matches',
      whereToSave: 'Unde salvăm imaginea?',
      cancel: 'Anulează',
      likeSwipeBtn: 'Apreciază ❤️'
    },
    coupons: {
      useCoupon: 'Folosești cuponul?',
      addNote: 'Adaugă o notă (opțional):',
      notePlaceholder: 'ex: azi seară, la 20:00...',
      later: 'Mai târziu',
      useIt: '✅ Folosesc!',
      createCoupon: '✨ Creează un Cupon',
      canBeUsedBy: 'Acest cupon va putea fi folosit de ',
      titlePlaceholder: 'Titlu (ex: Mic dejun la pat)',
      descPlaceholder: 'Descriere detaliată...',
      emojiPlaceholder: 'Emoji (ex: 🥞)',
      cancel: 'Renunță',
      save: 'Salvează',
      suggestCoupon: 'Sugerează un Cupon',
      whatCouponWant: 'Ce cupon ai vrea să primești în viitor? Scrie ideea ta mai jos.',
      suggestPlaceholder: 'ex: Mic dejun la pat...',
      sendSuggestion: 'Trimite Sugestia',
      usedStatus: '✓ Folosit',
      availableStatus: '✨ Disponibil',
      usedOn: '🗓️ Folosit pe ',
      tapToUse: 'Atinge pentru a folosi →',
      couponUsedTitle: 'Cupon Folosit 🎟️',
      usedCouponText: ' a folosit cuponul ',
      noteLabel: '📝 Notă: ',
      couponPrefix: 'Cupon „',
      usedSuccess: '” folosit! 🎉 Partenerul a primit notificarea.',
      useError: 'Eroare la folosirea cuponului',
      createSuccess: 'Cupon creat cu succes!',
      createError: 'Eroare la crearea cuponului',
      newSuggestionTitle: 'Sugestie Cupon Nou 💡',
      hey: 'Auzi, ',
      wouldLikeCouponFor: ' și-ar dori un cupon pentru: ',
      proposedCoupon: ' a propus un cupon: ',
      suggestSuccess: 'Sugestia ta a fost trimisă cu succes! 🎉',
      suggestError: 'Eroare la trimiterea sugestiei',
      defaultMassage: 'Masaj la spate',
      defaultMassageDesc: 'Un masaj relaxant de 15 minute.',
      defaultMovie: 'Film la alegere',
      defaultMovieDesc: 'Alegi tu la ce ne uităm în seara asta.',
      defaultOuting: 'Ieșire în oraș',
      defaultOutingDesc: 'O întâlnire în oraș la un restaurant ales de tine.',
      defaultFood: 'Alegi ce mâncăm',
      defaultFoodDesc: 'Mâncăm orice poftești tu astăzi.',
      defaultCuddle: 'Seară de cuddling',
      defaultCuddleDesc: '30 de minute de îmbrățișări și drăgălășenii.',
      defaultChore: 'Scutit(ă) de o sarcină',
      defaultChoreDesc: 'Te scap de o treabă prin casă azi.',
      addDefaultsSuccess: 'Cupoanele basic au fost adăugate!',
      addDefaultsError: 'Eroare la adăugarea cupoanelor.',
      pageTitle: 'Răsfăț & Cupoane 🎟️',
      pageSubtitle: 'Cadourile voastre de dragoste',
      suggestBtn: 'Sugerează',
      createBtn: 'Creează',
      received: '🎁 Primite',
      created: '✍️ Create',
      noReceived: 'Nu ai primit niciun cupon încă. Sugerează unul!',
      noCreated: 'Nu ai creat niciun cupon. Oferă un cadou partenerului!',
      adding: 'Se adaugă...',
      loadDefaults: '🪄 Încarcă cupoanele de bază'
    },
    nav: {
      home: 'Acasă',
      study: 'Studiu',
      chat: 'Mesaje',
      coupons: 'Cupoane',
      movies: 'Filme',
      homeplanner: 'Cuib',
      eu: 'Eu',
      todo: 'To-Do',
      memories: 'Amintiri',
      games: 'Idei',
      truthdare: 'T or D',
      profile: 'Profil',
      calendar: 'Calendar'
    },
    profile: {
      title: 'Profilul Tău',
      subtitle: 'Personalizează-ți colțul tău din aplicație',
      completed: 'completat',
      uploadingAvatar: 'Se încarcă (poate dura puțin)...',
      changeAvatar: '📷 Schimbă poza',
      realName: 'Nume real',
      bioLabel: 'Bio / Un gând drăguț',
      bioPlaceholder: 'Scrie ceva drăguț aici...',
      roLang: '🇷🇴 Română',
      enLang: '🇬🇧 Engleză',
      lang: 'Limba Aplicației',
      storage: 'Spațiu de stocare',
      storageUsed: 'MB folosiți',
      unlimited: 'Nelimitat',
      upgrade: 'Upgrade la PRO 👑',
      anniversary: 'Aniversarea voastră',
      anniversaryLabel: 'Suntem împreună din data de',
      nickname: 'Alint (cum vrei să te strig?)',
      birthdate: 'Data nașterii',
      color: 'Culoarea preferată',
      save: 'Salvează Modificările',
      saving: 'Se salvează...',
      saved: 'Modificările au fost salvate!',
      logout: 'Deconectare',
      changePass: 'Schimbă Parola',
      currentPass: 'Parola Curentă',
      newPass: 'Noua Parolă',
      newPassRules: 'Noua Parolă (min 6 caractere)',
      confirmPass: 'Confirmă parola',
      saveNewPass: 'Salvează Parola Nouă',
      passChangeBtn: 'Schimbă Parola 🔒',
      yourAccount: '✨ Contul Tău',
      proTitle: '👑 Ești utilizator PRO!',
      proDesc: 'Mulțumim pentru susținere! Toate reclamele sunt dezactivate și ai acces la funcțiile premium.',
      proUpgradeDesc: 'Treci la PRO pentru a elimina toate reclamele și a susține dezvoltarea aplicației noastre! 💕',
      buyPkg: 'Cumpără',
      loadingOffers: 'Se încarcă ofertele...',
      logoutDesc: 'Deconectarea te va scoate din acest cont. Vei avea nevoie de codul tău de pereche pentru a te reconecta.',
      logoutConfirm: 'Ești sigur că vrei să te deconectezi? Vei avea nevoie de codul tău pentru a intra înapoi.',
      logoutBtn: 'Deconectare',
      appVersion: 'Versiunea aplicației',
      newVersionAvailable: 'Este disponibilă o versiune nouă',
      downloadUpdate: 'Descarcă Update-ul',
      proThankYou: 'Mulțumim! Acum ești PRO! 👑',
      onboardingWelcome: 'Se pare că profilul tău nu este complet. Hai să adăugăm o poză!',
      onboardingBtn: 'Completează Profilul'
    },
    notifications: {
      eventTomorrowTitle: '🗓️ Mâine: {title}',
      eventTomorrowBody: 'Nu uita de evenimentul de mâine!',
      eventTodayTitle: '🗓️ Astăzi: {title}',
      eventTodayBody: 'Azi e ziua cea mare!',
      taskTodayTitle: '📅 Task pentru azi: {title}',
      taskTodayBody: 'Ai termen limită astăzi la ora {time}',
      taskSoonTitle: '⏳ Deadline în curând: {title}',
      taskSoonBody: 'A mai rămas o oră pentru a finaliza acest task!',
      inAppTaskTodayTitle: 'Task pentru azi: {title}',
      inAppTaskTodayBody: 'Ai termen limită la {time}',
      inAppTaskSoonTitle: 'Deadline în curând: {title}',
      inAppTaskSoonBody: 'A mai rămas mai puțin de o oră!',
      chatNewMessageTitle: '💬 Mesaj nou de la {name}',
      homeAddedTitle: '🏠 {title}',
      homeAddedBody: 'S-a adăugat: {task}',
      centerTitle: 'Notificări',
      empty: 'Nu ai nicio notificare.',
      fromYou: 'De la tine',
      fromPartner: 'De la {name}'
    },
    dashboard: {
      welcome: 'Bine ai venit',
      togetherSince: 'Suntem împreună de:',
      days: 'Zile',
      hours: 'Ore',
      mins: 'Min',
      secs: 'Sec',
      loading: 'Se încarcă...',
      shortcuts: 'Scurtături Rapide ⚡',
      games: 'Idei & Mâncare',
      truthDare: 'Adevăr / Provocare',
      ourState: 'Starea Noastră 📊',
      yourStress: 'Stresul tău:',
      partnerStress: 'Stres',
      buzzer: 'Buzzer Bună Dimineața 🐝',
      upcoming: 'Urmează',
      noEvents: 'Niciun eveniment programat.',
      openCalendar: 'Deschide Calendarul ›',
      complimentWrite: 'Scrie-i tu ceva ›',
      complimentCancel: 'Anulează',
      complimentSend: 'Trimite Complimentul 💌',
      sendComplimentPrompt: 'Trimite-i un compliment:',
      lastSent: 'Ultimul trimis:',
      writeNice: 'Scrie ceva frumos pentru',
      whatWeDo: 'Ce facem azi?',
      buzzSuccess: 'Buzz trimis cu succes!',
      buzzTitle: 'BUZZ! 🐝',
      buzzMsg: '🐝 Bzzzz! {{name}} îți trimite un Buzz! Bună dimineața sau... trezește-te!',
      partnerStateLabel: 'Starea',
      yourAnger: 'Nervii tăi:',
      anger: 'Nervi',
      newComplimentTitle: 'Compliment Nou 💌',
      newComplimentBody: 'Auzi, {{name}} a vrut să îți spună ceva frumos: "{{text}}"',
      receivedDrawing: 'Ai un desen nou! 🎁',
      deleteBtn: '🗑️ Șterge',
      saveMemoriesBtn: '❤️ Păstrează în Amintiri',
      drawSomething: 'Desenează ceva 🎨',
      sendBtn: 'Trimite ✈️',
      clearBtn: 'Șterge',
      scratchTitle: 'Surpriza Zilei',
      scratchSubtitle: 'Un nou loz în fiecare zi!',
      scratchLoading: 'Se încarcă surpriza...',
      scratchHere: 'Răzuiește aici! 💕',
      scratchComeBack: 'Revino mâine pentru un nou loz!',
      baristaTitle: 'Virtual Barista',
      baristaSubtitle: 'Trimite o cerere instant către partener',
      baristaCoffeeLabel: '☕ Cafea',
      baristaCoffeeMsg: 'Alertează! Am nevoie urgentă de o cafea! 🏃‍♂️',
      baristaAttentionLabel: '⚠️ Atenție',
      baristaAttentionMsg: 'Misiune importantă: am nevoie de atenție! 💕',
      baristaHugLabel: '🫂 Îmbrățișare',
      baristaHugMsg: 'Am nevoie de o îmbrățișare ACUM! 💕',
      baristaMassageLabel: '💆 Masaj',
      baristaMassageMsg: 'Sunt stresat/ă, am nevoie de un masaj magic! ✨',
      baristaSendBtn: 'Trimite cerere!',
      baristaSending: 'Se trimite...',
      baristaSent: 'Trimis! A primit! 💕',
      baristaCountOne: 'Ai trimis',
      baristaCountSingular: 'cerere',
      baristaCountPlural: 'cereri',
      baristaCountToday: 'azi 💕'
    },
    mood: {
      title: 'Cum te simți?',
      subtitle: 'va primi o notificare cu starea ta ✨',
      more: 'Mai exact? (opțional)',
      addNote: 'Adaugă un mesaj pentru',
      send: 'Trimite starea mea',
      sent: '✅ Trimis!',
      sending: '📲 Se trimite...',
      historyTitle: 'Istoric Stări',
      diaryTitle: 'Jurnal Privat',
      diaryUnlockMsg: 'Introdu parola contului tău pentru a debloca jurnalul tău intim.',
      diaryWarning: 'Atenție: Dacă uiți parola și folosești opțiunea de resetare pe email, vei pierde accesul la vechile intrări!',
      diaryUnlockBtn: '🔓 Deblochează',
      diaryEmpty: 'Prima ta amintire secretă așteaptă să fie scrisă.',
      diarySave: 'Salvează în jurnal',
      pageTitle: 'Spațiul Meu 🌸',
      pageSubtitle: 'Privat și doar pentru tine',
      tabMood: 'Cum mă simt',
      tabDiary: 'Jurnalul meu',
      diaryPlaceholder: 'Scrie gândurile tale... Doar tu le vei putea citi. 🌸',
      words: 'cuvinte',
      encrypting: '🔒 Se criptează...',
      saveCloud: '💾 Salvează în cloud',
      diaryLoading: 'Se încarcă din cloud...',
      diaryEmptyText: 'Prima ta intrare în jurnal te așteaptă.\nScrie ceva frumos! 💕',
      yourEntries: 'Intrările tale',
      decrypting: '🔓 Se decriptează local...',
      areYouSure: 'Ești sigură?',
      yes: 'Da',
      no: 'Nu',
      deleteBtn: '🗑️ Șterge',
      heWillReceive: 'El va primi o notificare cu starea ta ✨',
      sheWillReceive: 'Ea va primi o notificare cu starea ta ✨',
      moodCustomPlaceholderHer: 'Ex: Sunt foarte confuză...',
      moodCustomPlaceholderHis: 'Ex: Sunt foarte confuz...',
      addMessageHer: 'Adaugă un mesaj pentru el:',
      addMessageHis: 'Adaugă un mesaj pentru ea:',
      notePlaceholder: 'ex: Mă gândesc la tine 🥺...',
      sentMsg: '✅ Trimis! Partenerul tău știe acum 💕',
      moodAngryHer: 'Supărată',
      moodAngryHis: 'Supărat',
      moodSadHer: 'Tristă',
      moodSadHis: 'Trist',
      moodMeh: 'Meh',
      moodOkay: 'Ok',
      moodGood: 'Bine',
      moodGreat: 'Super',
      moodInLoveHer: 'Îndrăgostită',
      moodInLoveHis: 'Îndrăgostit',
      moodCustom: 'Altceva...',
      feelTiredHer: '😴 Obosită',
      feelTiredHis: '😴 Obosit',
      feelEnergeticHer: '💪 Energică',
      feelEnergeticHis: '💪 Energic',
      feelHappyHer: '🤗 Fericită',
      feelHappyHis: '🤗 Fericit',
      feelSensitiveHer: '🥺 Sensibilă',
      feelSensitiveHis: '🥺 Sensibil',
      feelFrustratedHer: '😤 Frustrată',
      feelFrustratedHis: '😤 Frustrat',
      feelRelaxedHer: '🌸 Relaxată',
      feelRelaxedHis: '🌸 Relaxat',
      feelExcitedHer: '🦋 Entuziasmată',
      feelExcitedHis: '🦋 Entuziasmat',
      feelCold: '🥶 Frig',
      feelSickHer: '🤒 Răcită',
      feelSickHis: '🤒 Răcit',
      feelInLoveHer: '💕 Îndrăgostită',
      feelInLoveHis: '💕 Îndrăgostit',
      feelCelebrating: '🎉 Sărbătorind',
      feelMeditativeHer: '🧘 Meditativă',
      feelMeditativeHis: '🧘 Meditativ'
    }
  },
  en: {
    login: {
      welcome: 'Welcome!',
      welcomeTitle: 'Couple Hub',
      howToCall: 'How should we call you?',
      connectPartner: 'Connect with your partner',
      placeholderName: 'Enter your name...',
      girl: 'Girl 👩',
      boy: 'Boy 👨',
      saving: 'Saving...',
      continueBtn: 'Continue',
      yourKey: 'Your pairing key:',
      sendKey: 'Send this key to your partner, or...',
      enterKey: 'Enter your partner\'s key:',
      placeholderKey: 'e.g: ABCDEF',
      youAreGirl: 'You are a Girl 👩',
      youAreBoy: 'You are a Boy 👨',
      connecting: 'Connecting...',
      connectBtn: 'Connect',
      loginTab: 'Login',
      registerTab: 'Register',
      emailLabel: 'Email',
      passLabel: 'Password',
      passRules: 'Password (min 6 characters)',
      forgotPass: 'Forgot password?',
      enterBtn: 'Sign In',
      registerBtn: 'Create Account',
      forgotText: 'We will send you a password reset link via email.',
      resetBtn: 'Reset Password',
      backToLogin: 'Back to Login',
      logout: 'Logout',
      autoUpdate: 'If your partner enters your key, the screen will update automatically!',
      backConfirm: 'Do you want to go back and change your name or gender? (This will generate a new key)',
      backBtn: 'Back',
      footer: 'Made with 💕 for you two',
      signIn: 'Sign In',
      createAcc: 'Create Account',
      errorEmail: 'Enter your email address',
      successReset: 'Password reset link sent to your email!',
      logoutConfirm: 'Do you want to log out?',
    },
    calendar: {
      months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      days: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
      deleteConfirm: 'Are you sure you want to delete this event?',
      loading: 'Loading Calendar...',
      eventsOn: 'Events on',
      title: 'Calendar 📅',
      subtitle: 'Our special days',
      hint: '💡 Tap on any day to add an event. Tap on an event to edit it.',
      editTitle: 'Edit Event ✏️',
      addTitle: 'Add Event ✨',
      defaultEventName: 'Event',
      addAnother: '+ Add another event on this day',
      eventNameLabel: 'Event Name',
      dateLabel: 'Date',
      recurrenceLabel: 'Repeat',
      recNone: 'Once only',
      recWeekly: 'Every 7 days',
      recMonthly: 'Every month',
      recYearly: 'Every year',
      detailsLabel: 'Details (optional)',
      detailsPlaceholder: 'More details about the event...',
      importanceLabel: 'Importance',
      high: 'High ❤️',
      medium: 'Medium 💛',
      low: 'Low 💙',
      saveBtn: 'Save',
      deleteBtn: 'Delete',
      cancelBtn: 'Cancel'
    },
    todo: {
      categories: {
        general: 'General',
        home: 'Home 🏠',
        work: 'Work 💼',
        shopping: 'Shopping 🛒',
        health: 'Health 💊',
        love: 'Love ❤️',
        other: 'Other'
      },
      loading: 'Loading...',
      title: '📝 To-Do List',
      subtitle: 'Your personal tasks',
      tabActive: 'Active',
      tabCompleted: 'History',
      sortImportance: '🔥 Sort: Importance',
      sortDeadline: '⏰ Sort: Deadline',
      sortCategory: '📂 Sort: Category',
      sortDateAdded: '📅 Sort: Date Added',
      sortName: '🔤 Sort: Name',
      addBtn: '➕ Add new task',
      emptyActive: 'You have no active tasks. Yay! 🎉',
      emptyCompleted: 'No completed tasks yet.',
      expired: 'Expired ⚠️',
      today: 'Today 🚨',
      importance: 'Importance:',
      impHigh: 'High',
      impMedium: 'Medium',
      impLow: 'Low',
      impHighEmoji: '🔥 High',
      impMediumEmoji: '⭐ Medium',
      impLowEmoji: '🧊 Low',
      editTask: 'Edit Task',
      newTask: 'New Task',
      titleLabel: 'Title *',
      titlePlaceholder: 'e.g. Buy flowers',
      categoryLabel: 'Category',
      otherCategory: 'Other category...',
      newCategoryPlaceholder: 'New category name...',
      deadlineLabel: 'Deadline',
      detailsLabel: 'Details (optional)',
      detailsPlaceholder: 'Additional details...',
      importanceLabel: 'Importance',
      imageLabel: 'Add an image (optional)',
      uploading: 'Uploading...',
      clickUpload: '📷 Tap to upload a photo',
      deleteImage: 'Delete image',
      saveChanges: 'Save changes',
      createTask: 'Create task',
      errorImage: 'Error uploading image.'
    },
    memories: {
      openMap: '🗺️ Open in Google Maps',
      commentsReactions: 'Comments & Reactions 💕',
      addReactionPlaceholder: 'Add a reaction...',
      send: 'Send',
      pleaseAddPhoto: 'Please add a photo!',
      pleaseClickMap: 'Please click on the map to choose a location!',
      errorImage: 'Error processing image',
      newPhoto: 'New photo',
      editMemory: 'Edit Memory ✏️',
      addPhotoGallery: 'Add Photo to Gallery 📸',
      addMemoryNew: 'Add New Memory ✨',
      locSelected: '📍 Location selected on map',
      locKept: '📍 Existing location kept',
      titlePlaceholder: 'Title (e.g. First Vacation)',
      descPlaceholder: 'Description...',
      emojiPlaceholder: 'Emoji (e.g. 🏖️)',
      changeSelectedPhoto: 'Change selected Photo',
      replaceCurrentPhoto: 'Replace current photo (Optional)',
      selectPhoto: 'Select a Photo (Required for Gallery)',
      cancel: 'Cancel',
      saving: 'Saving...',
      save: 'Save',
      add: 'Add',
      photoGallery: 'Photo Gallery 📸',
      addOnlyPhoto: '+ Add only a Photo',
      noPhotosYet: 'You have no photos added yet.',
      loadingMemories: 'Loading memories...',
      confirmDelete: 'Are you sure you want to delete this memory/photo?',
      ourMemories: 'Our Memories 💕',
      specialPlaces: 'Special places and moments',
      mapHint: '💡 Tap anywhere on the map to add a new memory!',
      savedLocations: 'Saved Locations 📍',
      noMemoriesOnMap: 'No memories on the map yet.'
    },
    messages: {
      loading: 'Loading messages...',
      seenAt: 'Seen at ',
      seen: 'Seen',
      back: 'Back',
      typing: 'is typing...',
      writeMessagePlaceholder: 'Write a message...',
      birthday: '🎂 Birthday:',
      favColor: '🎨 Favorite color:',
      backToChat: 'Back to chat'
    },
    games: {
      noOptions: 'No options',
      wheelAriaLabel: 'Wheel of fortune',
      spinning: '⏳ Spinning...',
      spin: '🎲 Spin!',
      finalDecision: 'Final decision:',
      tryAgain: '🔄 Try again',
      addNewOption: 'Add New Option',
      pizzaPlaceholder: 'e.g. Pizza',
      bgColor: 'Background color:',
      cancel: 'Cancel',
      add: 'Add',
      todaysOptions: 'Today\'s options:',
      addBtn: '+ Add',
      noOptionsAddSome: 'No options. Add some!',
      ideasFood: 'Ideas & Food 💡',
      letFateDecide: 'Let fate decide for you',
      foodTab: '🍔 Food',
      datesTab: '🌹 Dates',
      loading: 'Loading...',
      loadDefaultsBtn: '🪄 Load default ideas',
      foodTitle: 'What are we eating tonight? 🍽️',
      foodSubtitle: 'Tap the wheel and let fate decide!',
      dateTitle: 'What are we doing today? 🌹',
      dateSubtitle: 'A perfect date idea!',
      defaults: {
        food: ['Pizza 🍕', 'Sushi 🍣', 'Burger 🍔', 'Pasta 🍝', 'Chinese 🍜', 'Salad 🥗'],
        date: ['Movie at home 🎬', 'Walk 🚶', 'Cook something 👨‍🍳', 'Video games 🎮', 'Go out in the city 🍷', 'Home Spa 💆‍♀️']
      }
    },
    truthDare: {
      noOptions: 'No options',
      wheelAriaLabel: 'Wheel of fortune',
      spinning: '⏳ Spinning...',
      spin: '🎲 Spin!',
      yourChallengeIs: 'Your challenge is:',
      tryAgain: '🔄 Try again',
      addQuestion: 'Add a question',
      bgColor: 'Background color:',
      cancel: 'Cancel',
      add: 'Add',
      availableQuestions: 'Available questions/dares:',
      addBtn: '+ Add',
      noOptionsAddSome: 'No options. Add some!',
      title: 'Truth or Dare 🎭',
      subtitle: 'Who dares... wins 😈',
      truthTab: '🤍 Truth',
      dareTab: '🔥 Dare',
      loading: 'Loading...',
      truthTitle: 'Truth 🤍',
      truthSubtitle: 'The wheel chooses the question. You cannot lie!',
      dareTitle: 'Dare 🔥',
      dareSubtitle: 'The wheel chooses the dare. Be brave!',
      truthPlaceholder: 'e.g. What is your biggest secret?',
      darePlaceholder: 'e.g. Do 10 squats right now!',
      defaults: {
        truths: [
          'What is your biggest secret?',
          'What scares you the most in life?',
          'What is your most embarrassing moment?',
          'If you could change something about yourself, what would it be?',
          'What is your biggest unfulfilled dream?',
          'What quality do you appreciate the most in me?',
          'What is your favorite memory with us?',
          'What attracted you to me first?',
          'The biggest secret you haven\'t told anyone?',
          'How do you imagine our life in 10 years?'
        ],
        dares: [
          'Mime your favorite movie character!',
          'Sing 30s of your favorite song!',
          'Do 10 pushups right now!',
          'Say 3 things you admire about me!',
          'Dance for 1 minute without music!',
          'Speak with an accent for 2 minutes!',
          'Take a funny picture and send it to me!',
          'Imitate 3 different emojis!',
          'Say as many words as possible in 30 seconds!',
          'Tell a joke (good or bad)!'
        ]
      }
    },
    movies: {
      recommendationsTitle: 'Recommendations',
      library: 'Library',
      coupleMatch: 'Couple Match',
      searchPlaceholder: 'Search for a movie or TV show...',
      recommendedForYou: 'Recommended for you ✨',
      seeMore: 'See more ➔',
      likeSomeMovies: 'Like (❤️) some movies or TV shows to get personalized recommendations!',
      popularNow: 'Popular Now 🔥',
      loading: 'Loading...',
      exploreCatalog: 'Explore Catalog ➔',
      moviesFound: 'Movies Found',
      tvFound: 'TV Shows Found',
      noResults: 'No results found.',
      noOverview: 'No description available.',
      cast: 'Cast',
      noPicture: 'No Picture',
      watchTrailer: '▶️ Watch Trailer',
      notForMe: 'Not for me',
      addToMyList: 'Add to My List',
      saved: '✅ Saved',
      add: '❤️ Add',
      like: 'Like',
      liked: '✅ You Liked',
      likeBtn: '❤️ Like',
      youLikeIt: 'You like it',
      inYourList: 'In Your List',
      emptyLibrary: 'Library is empty',
      emptyLibraryDesc: 'Movies you like (❤️) will appear here so you can watch them later.',
      searchMovies: 'Find Movies',
      loadingDetails: 'Loading details...',
      removeFromList: '❌ Remove from List'
    },
    studyLobby: {
      todo: 'To Do',
      inProgress: 'In Progress',
      done: 'Done ✓',
      preparingRoom: 'Preparing study room...',
      studyRoom: '📚 Study Room',
      offline: 'offline',
      lobby: '🌳 Lobby',
      tasksTab: '📋 Tasks',
      bonsaiInfoTitle: 'How does the Bonsai grow?',
      bonsaiInfo1: 'Your little tree (Bonsai) is a reflection of the time spent learning or working.',
      bonsaiInfo2a: 'for every ',
      bonsaiInfo2b: '1 minute',
      bonsaiInfo2c: ' of focus completed by either of you.',
      bonsaiInfo3a: 'If you both study ',
      bonsaiInfo3b: 'at the same time',
      bonsaiInfo3c: ', you get a bonus of ',
      bonsaiInfo3d: '+50% XP',
      bonsaiInfo3e: '!',
      bonsaiInfo4: 'Points are added to a shared pool (Total XP). The Bonsai has multiple stages, which unlock as you grow your XP.',
      stageSeed: 'Seed',
      stageSprout: 'Sprout',
      stageSapling: 'Sapling',
      stageYoungTree: 'Young Tree',
      stageMature: 'Mature Bonsai',
      stageAncient: 'Ancient Bonsai',
      stageLegendary: 'Tree of Love',
      stageBush: 'Bush',
      stageTree: 'Tree',
      stageBlossom: 'Blossoming Bonsai',
      bonsaiInfo5: 'Stay focused and let the little tree grow alongside you! 🌱',
      sessionsCompletedText: 'sessions completed',
      bonusCoStudy: '+50% XP bonus co-study!',
      sessionSettings: 'Session Settings',
      workMin: 'Work (min)',
      breakMin: 'Break (min)',
      cycles: 'Cycles',
      hurray: '🎉 Hurray!',
      finishedAllCycles1: 'You finished all ',
      finishedAllCycles2: ' study cycles!',
      startNewSession: 'Start a new session',
      focusTime: '💻 Focus Time',
      breakTime: '☕ Break',
      cycle: 'Cycle',
      of: 'of',
      minFocus: 'min focus',
      minBreak: 'min break',
      start: '▶ Start',
      pause: '⏸ Pause',
      reset: '↻ Reset',
      skipToBreak: '⏭ Skip to Break',
      skipToWork: '⏭ Skip to Work',
      music: '🎵 Music',
      on: '🔊 On',
      off: '🔇 Off',
      change: 'Change ▾',
      radioLoop: 'Radio / Audio Loop',
      audioNotSupported: 'Your browser does not support the audio element.',
      searchYoutube: '▶️ Search on YouTube',
      myTasks: 'My Tasks',
      whatToDo: 'What do you have to do?',
      subjectOptional: 'Subject (optional)',
      addBtn: 'Add',
      noTasksYet: 'No tasks yet. Add one! 📝',
      deleteTaskPrompt: 'Delete this task?',
      partnerNoTasks: 'has no tasks yet.'
    },
    homePlanner: {
      kitchen: 'Kitchen',
      living: 'Living Room',
      bedroom: 'Bedroom',
      bathroom: 'Bathroom',
      hallway: 'Hallway',
      balcony: 'Balcony',
      attic: 'Attic',
      office: 'Office',
      freeSearches: 'Free Searches',
      superMatchTitlePush: 'Design Super Match! 🌟',
      superMatchBodyPush: 'A new match was created: ',
      superMatchTitleInApp: 'Super Match! 🌟',
      superMatchBodyInApp: 'You both liked: ',
      loadingProject: 'Loading project...',
      saved: 'saved',
      all: 'All',
      addedItems: 'Added Items 🛒',
      openLink: '🔗 Open Link',
      noPicture: '🔗 No Picture',
      viewLink: '🔗 View Link',
      swipeIdeas: 'Swipe Ideas 💡',
      link: '🔗 Link',
      emptyRoom: 'You haven\'t saved anything here yet. Use the + button or Swipe.',
      ourProject: 'Our Project 🏠',
      totalIdeasSaved: 'Total ideas saved: ',
      ideasAddedByYou: 'Ideas/Links added by you: ',
      superMatches: 'Super Matches: ',
      estimatedCost: '💰 Estimated cumulative cost: ~',
      searchSavedIdeas: 'Search in saved ideas (by title, tag or link)...',
      rooms: 'Rooms',
      item: 'item',
      items: 'items',
      currency: 'RON',
      searchResults: 'Search Results',
      noIdeasFor: 'I couldn\'t find any idea for ',
      searchLabel: 'Search: ',
      searchPlaceholderSwipe: 'Search in English for best results (e.g., black sofa)...',
      orChooseRoom: 'Or choose a room:',
      backBtn: '← Back',
      searchingPremiumIdeas: 'Searching for premium ideas... ⏳',
      planBWarning: '⚠️ Using local Pinterest (Plan B)',
      seenItAll: 'You\'ve seen it all!',
      searchMore: 'Search more',
      noMatchesYet: 'You don\'t have any mutually approved matches yet.',
      approvedDecisions: 'Approved Decisions (Matches) 🌟',
      homePlannerTitle: 'Home Planner 🏡',
      homePlannerSubtitle: 'The project for our nest',
      projectTab: 'Project',
      inspirationTab: 'Inspiration',
      matchesTab: 'Matches',
      whereToSave: 'Where should we save the image?',
      cancel: 'Cancel',
      likeSwipeBtn: 'Like ❤️'
    },
    coupons: {
      useCoupon: 'Use coupon?',
      addNote: 'Add a note (optional):',
      notePlaceholder: 'e.g. tonight at 8 PM...',
      later: 'Later',
      useIt: '✅ Use it!',
      createCoupon: '✨ Create a Coupon',
      canBeUsedBy: 'This coupon can be used by ',
      titlePlaceholder: 'Title (e.g. Breakfast in bed)',
      descPlaceholder: 'Detailed description...',
      emojiPlaceholder: 'Emoji (e.g. 🥞)',
      cancel: 'Cancel',
      save: 'Save',
      suggestCoupon: 'Suggest a Coupon',
      whatCouponWant: 'What coupon would you like to receive in the future? Write your idea below.',
      suggestPlaceholder: 'e.g. Breakfast in bed...',
      sendSuggestion: 'Send Suggestion',
      usedStatus: '✓ Used',
      availableStatus: '✨ Available',
      usedOn: '🗓️ Used on ',
      tapToUse: 'Tap to use →',
      couponUsedTitle: 'Coupon Used 🎟️',
      usedCouponText: ' used the coupon ',
      noteLabel: '📝 Note: ',
      couponPrefix: 'Coupon "',
      usedSuccess: '" used! 🎉 Your partner received a notification.',
      useError: 'Error using the coupon',
      createSuccess: 'Coupon created successfully!',
      createError: 'Error creating the coupon',
      newSuggestionTitle: 'New Coupon Suggestion 💡',
      hey: 'Hey, ',
      wouldLikeCouponFor: ' would like a coupon for: ',
      proposedCoupon: ' proposed a coupon: ',
      suggestSuccess: 'Your suggestion was sent successfully! 🎉',
      suggestError: 'Error sending the suggestion',
      defaultMassage: 'Back massage',
      defaultMassageDesc: 'A relaxing 15-minute massage.',
      defaultMovie: 'Movie of choice',
      defaultMovieDesc: 'You choose what we watch tonight.',
      defaultOuting: 'Night out',
      defaultOutingDesc: 'A date night at a restaurant of your choice.',
      defaultFood: 'You choose the food',
      defaultFoodDesc: 'We eat whatever you crave today.',
      defaultCuddle: 'Cuddle evening',
      defaultCuddleDesc: '30 minutes of cuddling and sweetness.',
      defaultChore: 'Excused from a chore',
      defaultChoreDesc: 'I will take over a house chore for you today.',
      addDefaultsSuccess: 'Basic coupons have been added!',
      addDefaultsError: 'Error adding coupons.',
      pageTitle: 'Pampering & Coupons 🎟️',
      pageSubtitle: 'Your gifts of love',
      suggestBtn: 'Suggest',
      createBtn: 'Create',
      received: '🎁 Received',
      created: '✍️ Created',
      noReceived: 'You haven\'t received any coupons yet. Suggest one!',
      noCreated: 'You haven\'t created any coupons. Give your partner a gift!',
      adding: 'Adding...',
      loadDefaults: '🪄 Load basic coupons'
    },
    nav: {
      home: 'Home',
      study: 'Study',
      chat: 'Messages',
      coupons: 'Coupons',
      movies: 'Movies',
      homeplanner: 'Nest',
      eu: 'Me',
      todo: 'To-Do',
      memories: 'Memories',
      games: 'Ideas',
      truthdare: 'T or D',
      profile: 'Profile',
      calendar: 'Calendar'
    },
    profile: {
      title: 'Your Profile',
      subtitle: 'Customize your corner of the app',
      completed: 'completed',
      uploadingAvatar: 'Uploading (might take a bit)...',
      changeAvatar: '📷 Change picture',
      realName: 'Real name',
      bioLabel: 'Bio / A sweet thought',
      bioPlaceholder: 'Write something sweet here...',
      roLang: '🇷🇴 Romanian',
      enLang: '🇬🇧 English',
      lang: 'App Language',
      storage: 'Storage Space',
      storageUsed: 'MB used',
      unlimited: 'Unlimited',
      upgrade: 'Upgrade to PRO 👑',
      anniversary: 'Your Anniversary',
      anniversaryLabel: 'Together since',
      nickname: 'Nickname',
      birthdate: 'Birth Date',
      color: 'Favorite Color',
      save: 'Save Changes',
      saving: 'Saving...',
      saved: 'Changes saved successfully!',
      logout: 'Log Out',
      changePass: 'Change Password',
      currentPass: 'Current Password',
      newPass: 'New Password',
      newPassRules: 'New Password (min 6 characters)',
      confirmPass: 'Confirm Password',
      saveNewPass: 'Save New Password',
      passChangeBtn: 'Change Password 🔒',
      yourAccount: '✨ Your Account',
      proTitle: '👑 You are a PRO user!',
      proDesc: 'Thank you for your support! All ads are disabled and you have access to premium features.',
      proUpgradeDesc: 'Go PRO to remove all ads and support the development of our app! 💕',
      buyPkg: 'Buy',
      loadingOffers: 'Loading offers...',
      logoutDesc: 'Logging out will remove this account from the device. You will need your pairing key to reconnect.',
      logoutConfirm: 'Are you sure you want to log out? You will need your code to log back in.',
      logoutBtn: 'Log Out',
      appVersion: 'App version',
      newVersionAvailable: 'A new version is available',
      downloadUpdate: 'Download Update',
      proThankYou: 'Thank you! You are now PRO! 👑',
      onboardingWelcome: 'It looks like your profile is not complete. Let\'s add a photo!',
      onboardingBtn: 'Complete Profile'
    },
    notifications: {
      eventTomorrowTitle: '🗓️ Tomorrow: {title}',
      eventTomorrowBody: 'Don\'t forget about tomorrow\'s event!',
      eventTodayTitle: '🗓️ Today: {title}',
      eventTodayBody: 'Today is the big day!',
      taskTodayTitle: '📅 Task for today: {title}',
      taskTodayBody: 'You have a deadline today at {time}',
      taskSoonTitle: '⏳ Deadline soon: {title}',
      taskSoonBody: 'You have one hour left to finish this task!',
      inAppTaskTodayTitle: 'Task for today: {title}',
      inAppTaskTodayBody: 'You have a deadline at {time}',
      inAppTaskSoonTitle: 'Deadline soon: {title}',
      inAppTaskSoonBody: 'Less than an hour left!',
      chatNewMessageTitle: '💬 New message from {name}',
      homeAddedTitle: '🏠 {title}',
      homeAddedBody: 'Added: {task}',
      centerTitle: 'Notifications',
      empty: 'You have no new notifications.',
      fromYou: 'From you',
      fromPartner: 'From {name}'
    },
    dashboard: {
      welcome: 'Welcome',
      togetherSince: 'Together for:',
      days: 'Days',
      hours: 'Hrs',
      mins: 'Min',
      secs: 'Sec',
      loading: 'Loading...',
      shortcuts: 'Quick Shortcuts ⚡',
      games: 'Ideas & Food',
      truthDare: 'Truth / Dare',
      ourState: 'Our State 📊',
      yourStress: 'Your Stress:',
      partnerStress: 'Stress',
      buzzer: 'Good Morning Buzzer 🐝',
      upcoming: 'Upcoming',
      noEvents: 'No upcoming events.',
      openCalendar: 'Open Calendar ›',
      complimentWrite: 'Write something ›',
      complimentCancel: 'Cancel',
      complimentSend: 'Send Compliment 💌',
      sendComplimentPrompt: 'Send a compliment:',
      lastSent: 'Last sent:',
      writeNice: 'Write something sweet for',
      whatWeDo: 'What are we doing today?',
      buzzSuccess: 'Buzz sent successfully!',
      buzzTitle: 'BUZZ! 🐝',
      buzzMsg: '🐝 Bzzzz! {{name}} is sending you a Buzz! Good morning or... wake up!',
      partnerStateLabel: 'Status of',
      yourAnger: 'Your Anger:',
      anger: 'Anger',
      newComplimentTitle: 'New Compliment 💌',
      newComplimentBody: 'Hey, {{name}} wanted to tell you something sweet: "{{text}}"',
      receivedDrawing: 'New Drawing Received! 🎁',
      deleteBtn: '🗑️ Discard',
      saveMemoriesBtn: '❤️ Save to Memories',
      drawSomething: 'Draw something 🎨',
      sendBtn: 'Send ✈️',
      clearBtn: 'Clear',
      scratchTitle: 'Daily Surprise',
      scratchSubtitle: 'A new scratch card every day!',
      scratchLoading: 'Loading surprise...',
      scratchHere: 'Scratch here! 💕',
      scratchComeBack: 'Come back tomorrow for a new scratch card!',
      baristaTitle: 'Virtual Barista',
      baristaSubtitle: 'Send an instant request to your partner',
      baristaCoffeeLabel: '☕ Coffee',
      baristaCoffeeMsg: 'Alert! I desperately need coffee! 🏃‍♂️',
      baristaAttentionLabel: '⚠️ Attention',
      baristaAttentionMsg: 'Important mission: I need attention! 💕',
      baristaHugLabel: '🫂 Hug',
      baristaHugMsg: 'I need a hug RIGHT NOW! 💕',
      baristaMassageLabel: '💆 Massage',
      baristaMassageMsg: 'I am stressed, I need a magic massage! ✨',
      baristaSendBtn: 'Send request!',
      baristaSending: 'Sending...',
      baristaSent: 'Sent! Received! 💕',
      baristaCountOne: 'You sent',
      baristaCountSingular: 'request',
      baristaCountPlural: 'requests',
      baristaCountToday: 'today 💕'
    },
    mood: {
      title: 'How do you feel?',
      subtitle: 'will receive a notification with your mood ✨',
      more: 'More specifically? (optional)',
      addNote: 'Add a message for',
      send: 'Send my mood',
      sent: '✅ Sent!',
      sending: '📲 Sending...',
      historyTitle: 'Mood History',
      diaryTitle: 'Private Diary',
      diaryUnlockMsg: 'Enter your account password to unlock your private diary.',
      diaryWarning: 'Warning: If you forget your password and use the email reset option, you will lose access to old entries!',
      diaryUnlockBtn: '🔓 Unlock',
      diaryEmpty: 'Your first diary entry is waiting.',
      diarySave: 'Save entry',
      pageTitle: 'My Space 🌸',
      pageSubtitle: 'Private and just for you',
      tabMood: 'How I feel',
      tabDiary: 'My Diary',
      diaryPlaceholder: 'Write your thoughts... Only you can read them. 🌸',
      words: 'words',
      encrypting: '🔒 Encrypting...',
      saveCloud: '💾 Save to cloud',
      diaryLoading: 'Loading from cloud...',
      diaryEmptyText: 'Your first diary entry is waiting.\nWrite something sweet! 💕',
      yourEntries: 'Your entries',
      decrypting: '🔓 Decrypting locally...',
      areYouSure: 'Are you sure?',
      yes: 'Yes',
      no: 'No',
      deleteBtn: '🗑️ Delete',
      heWillReceive: 'He will receive a notification with your mood ✨',
      sheWillReceive: 'She will receive a notification with your mood ✨',
      moodCustomPlaceholderHer: 'Ex: I am very confused...',
      moodCustomPlaceholderHis: 'Ex: I am very confused...',
      addMessageHer: 'Add a message for him:',
      addMessageHis: 'Add a message for her:',
      notePlaceholder: 'ex: Thinking of you 🥺...',
      sentMsg: '✅ Sent! Your partner knows now 💕',
      moodAngryHer: 'Angry',
      moodAngryHis: 'Angry',
      moodSadHer: 'Sad',
      moodSadHis: 'Sad',
      moodMeh: 'Meh',
      moodOkay: 'Ok',
      moodGood: 'Good',
      moodGreat: 'Great',
      moodInLoveHer: 'In Love',
      moodInLoveHis: 'In Love',
      moodCustom: 'Something else...',
      feelTiredHer: '😴 Tired',
      feelTiredHis: '😴 Tired',
      feelEnergeticHer: '💪 Energetic',
      feelEnergeticHis: '💪 Energetic',
      feelHappyHer: '🤗 Happy',
      feelHappyHis: '🤗 Happy',
      feelSensitiveHer: '🥺 Sensitive',
      feelSensitiveHis: '🥺 Sensitive',
      feelFrustratedHer: '😤 Frustrated',
      feelFrustratedHis: '😤 Frustrated',
      feelRelaxedHer: '🌸 Relaxed',
      feelRelaxedHis: '🌸 Relaxed',
      feelExcitedHer: '🦋 Excited',
      feelExcitedHis: '🦋 Excited',
      feelCold: '🥶 Cold',
      feelSickHer: '🤒 Sick',
      feelSickHis: '🤒 Sick',
      feelInLoveHer: '💕 In Love',
      feelInLoveHis: '💕 In Love',
      feelCelebrating: '🎉 Celebrating',
      feelMeditativeHer: '🧘 Meditative',
      feelMeditativeHis: '🧘 Meditative'
    }
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const authState = useGlobalAuth() || {};
  const { role } = authState;
  const { profile } = useProfiles(role);
  const [lang, setLang] = useState('ro');

  useEffect(() => {
    if (profile?.language && translations[profile.language]) {
      setLang(profile.language);
    }
  }, [profile?.language]);

  const t = (keyPath) => {
    const keys = keyPath.split('.');
    let current = translations[lang];
    for (const key of keys) {
      if (current[key] === undefined) {
        return keyPath; // fallback la cheie daca nu gaseste traducerea
      }
      current = current[key];
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
